name: ci-config
on:
  push:
    tags:
      - "gfmod-fa-app-v*"

  pull_request:
    branches:
      - main
      - "!release-please--*
    paths:
      - "src/app/**"
      - "!**/CHANGELOG.md"
      - "!.release-please-manifest.json"
    types: [opened, synchronize, reopened]
 
permissions:
  contents: read # git permissions to repo pull/push
  id-token: write # generate OIDC tokens for authentication
  checks: write # read/write to repo custom statuses and checks
  pull-requests: write # modify or update pull requests
  actions: read
  security-events: write
  issues: write
 
jobs:
  lint:
    #if: github.event_name != 'pull_request' || !startsWith(github.head_ref, 'release-please--')
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v5

  jf-setprops:
    needs: [lint]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Gitcheckout
        uses: actions/checkout@v5
 
